## Deliverable 2. Create a Customer Travel Destinations Map.

In [8]:
# Dependencies and Setup

import pandas as pd
import gmaps
import gmaps.datasets
import requests



# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [9]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Weather description
0,0,Bathsheba,13.2167,-59.5167,81.21,78,40,13.80,BB,2021-11-28 05:36:55,scattered clouds
1,1,Ushuaia,-54.8000,-68.3000,49.66,57,75,18.41,AR,2021-11-28 05:36:55,light rain
2,2,Rawson,-43.3002,-65.1023,55.74,78,0,5.44,AR,2021-11-28 05:36:56,clear sky
3,3,Sitka,57.0531,-135.3300,35.49,87,90,3.44,US,2021-11-28 05:36:56,light rain
4,4,Hermanus,-34.4187,19.2345,65.25,88,96,12.55,ZA,2021-11-28 05:36:57,overcast clouds

In [10]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 80

In [11]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Weather description
4,4,Hermanus,-34.4187,19.2345,65.25,88,96,12.55,ZA,2021-11-28 05:36:57,overcast clouds
14,14,Sao Filipe,14.8961,-24.4956,76.39,73,85,9.69,CV,2021-11-28 05:34:16,overcast clouds
19,19,Bredasdorp,-34.5322,20.0403,67.82,76,90,16.40,ZA,2021-11-28 05:34:14,overcast clouds
21,21,Port Alfred,-33.5906,26.8910,74.46,52,43,9.31,ZA,2021-11-28 05:37:02,scattered clouds
24,24,Mitha Tiwana,32.2486,72.1108,74.12,20,18,2.08,PK,2021-11-28 05:37:04,few clouds
...,...,...,...,...,...,...,...,...,...,...,...
679,679,Parintins,-2.6283,-56.7358,74.32,94,100,0.25,BR,2021-11-28 05:55:49,overcast clouds
681,681,Kindu,-2.9500,25.9500,69.67,98,100,1.10,CD,2021-11-28 05:55:50,light rain
683,683,Zambezi,-13.5432,23.1047,70.79,76,68,7.87,ZM,2021-11-28 05:55:50,broken clouds
693,693,Rumphi,-11.0186,33.8575,75.27,59,68,6.89,MW,2021-11-28 05:55:54,broken clouds
694,694,Quirinopolis,-18.4483,-50.4517,71.83,82,16,1.90,BR,2021-11-28 05:55:54,few clouds

In [12]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                265
City                   265
Lat                    265
Lng                    265
Max Temp               265
Humidity               265
Cloudiness             265
Wind Speed             265
Country                265
Date                   265
Weather description    265
dtype: int64

In [13]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
hotel_df=preferred_cities_df.dropna(how='any')

In [14]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    
    
   
    # Get the latitude and longitude.
  
    
  
    
    # Make request and get the JSON data from the search.
    
# Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [21]:
hotel_df.head(5)

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Weather description,Hotel Name
4,4,Hermanus,-34.4187,19.2345,65.25,88,96,12.55,ZA,2021-11-28 05:36:57,overcast clouds,Misty Waves Boutique Hotel
14,14,Sao Filipe,14.8961,-24.4956,76.39,73,85,9.69,CV,2021-11-28 05:34:16,overcast clouds,Hotel Xaguate
19,19,Bredasdorp,-34.5322,20.0403,67.82,76,90,16.40,ZA,2021-11-28 05:34:14,overcast clouds,Bredasdorp Country Manor
21,21,Port Alfred,-33.5906,26.8910,74.46,52,43,9.31,ZA,2021-11-28 05:37:02,scattered clouds,The Halyards Hotel
24,24,Mitha Tiwana,32.2486,72.1108,74.12,20,18,2.08,PK,2021-11-28 05:37:04,few clouds,Canal Rest House

In [17]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df=hotel_df.dropna(how='any')
hotel_df.isnull().sum()

City_ID                0
City                   0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Country                0
Date                   0
Weather description    0
Hotel Name             0
dtype: int64

In [22]:
hotel_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Weather description,Hotel Name
4,4,Hermanus,-34.4187,19.2345,65.25,88,96,12.55,ZA,2021-11-28 05:36:57,overcast clouds,Misty Waves Boutique Hotel
14,14,Sao Filipe,14.8961,-24.4956,76.39,73,85,9.69,CV,2021-11-28 05:34:16,overcast clouds,Hotel Xaguate
19,19,Bredasdorp,-34.5322,20.0403,67.82,76,90,16.40,ZA,2021-11-28 05:34:14,overcast clouds,Bredasdorp Country Manor
21,21,Port Alfred,-33.5906,26.8910,74.46,52,43,9.31,ZA,2021-11-28 05:37:02,scattered clouds,The Halyards Hotel
24,24,Mitha Tiwana,32.2486,72.1108,74.12,20,18,2.08,PK,2021-11-28 05:37:04,few clouds,Canal Rest House
...,...,...,...,...,...,...,...,...,...,...,...,...
679,679,Parintins,-2.6283,-56.7358,74.32,94,100,0.25,BR,2021-11-28 05:55:49,overcast clouds,Cama e Cafe
681,681,Kindu,-2.9500,25.9500,69.67,98,100,1.10,CD,2021-11-28 05:55:50,light rain,Résidence Okanda
683,683,Zambezi,-13.5432,23.1047,70.79,76,68,7.87,ZM,2021-11-28 05:55:50,broken clouds,Royal Kutachika Lodge
693,693,Rumphi,-11.0186,33.8575,75.27,59,68,6.89,MW,2021-11-28 05:55:54,broken clouds,Finst Rumphi Earthbag House Lodge
694,694,Quirinopolis,-18.4483,-50.4517,71.83,82,16,1.90,BR,2021-11-28 05:55:54,few clouds,Rota Hotéis - Quirinópolis GO

In [ ]:
# 8a. Create the output File (CSV)
hotel_df.to_csv('WeatherPy_vacation.csv') # it exports the DataFrame to excel CSV

In [ ]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
<dt>Weather description</dt><dd>{Weather description} °F</dd>
</dl>
"""

In [ ]:
# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [ ]:
# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# 11a. Add a marker layer for each city to the map. 
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)



# 11b. Display the figure
fig